### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by yesmeck** [JonGretar/ExDocDash#1]
Hello @JonGretar , I'm new to Elixir, just can not figure out how to use this package.

**Comment by JonGretar** [comment]
Thanks for pointing it out. I've added usage help in the [README](https://github.com/JonGretar/ExDocDash/blob/master/README.md).
Also noticed some issue with mix not installing sqlite3 so added info about that there as well.

Please let me know if you can generate docs using this new installation instructions.

**Comment by yesmeck** [comment]
It works.
But have a little issue, I'm tring to generate Phoenix docs, Phoenix depends on ex_doc `~> 0.6` and ExDocDash depends on ex_docs `>= 0.6.1`, this case a dependency conflicts.

**Comment by yesmeck** [comment]
BTW, It's Phoenix v0.7.2.

**Comment by JonGretar** [comment]
Yeah. That should be compatible. Phoenix requires anything over 0.6.0+ so 0.6.1 should satisfy it's dependencies. The problem probably lies in 0.6.0 having been installed in your deps folder before(Guessing you set up Phoenix a while ago when 0.6.0 was the latest version). Simply remove your `./deps` folder and do `MIX_ENV=docs mix deps.install` again. The `deps.update` task might also solve this.

**Comment by yesmeck** [comment]
Yes, `deps.update` solve the problem.

Is it possible to install this package as a archive by using `mix archive.build` and `mix archive install ex_doc_dash-0.1.0.ez`? So that we don't need modify other mix package's mix.exs and can directly run `MIX_ENV=docs mix docs.dash` under other mix package's directory.

**Comment by yesmeck** [comment]
I've tried `mix archive.build` and `mix archive install ex_doc_dash-0.1.0.ez`. But when I run `MIX_ENV=docs mix docs.dash` under Phoenix's directory, it raise a UndefinedFunctionError:

``` bash
** (UndefinedFunctionError) undefined function: :sqlite3.open/2 (module :sqlite3 is not available)
    :sqlite3.open(:index, [file: '/Users/meck/Workspace/codes/phoenix/docs/Phoenix 0.7.2.docset/Contents/Resources/docSet.dsidx'])
    lib/ex_doc_dash/formatter/dash.ex:57: ExDocDash.Formatter.Dash.create_index_database/1
    lib/ex_doc_dash/formatter/dash.ex:16: ExDocDash.Formatter.Dash.run/2
    lib/mix/tasks/docs.dash.ex:44: Mix.Tasks.Docs.Dash.run/3
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2
```

**Comment by JonGretar** [comment]
Are you sure `archive.install` installs dependent packages? Don't think it does.

**Comment by yesmeck** [comment]
It doesn't. I'm just wondering is that way possible. 
I think this issue can close now, thank you.
